version: '3.6'

services:
  postgres:
    container_name: ddev-${DDEV_SITENAME}-postgres
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - default

  pact-broker:
    container_name: ddev-${DDEV_SITENAME}-pact-broker
    image: "pactfoundation/pact-broker:2.110.0-pactbroker2.107.1"
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_PORT: '9292'
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      PACT_BROKER_BASE_URL: 'https://localhost http://localhost http://localhost:9292 http://pact-broker:9292 https://host.docker.internal http://host.docker.internal http://host.docker.internal:9292'
    networks:
      - default
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

  # Uncomment this section if you need Nginx
  # nginx:
  #   image: nginx:alpine
  #   depends_on:
  #     - pact-broker
  #   volumes:
  #     - "./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
  #     - "./ssl:/etc/nginx/ssl"
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - default

networks:
  default:
    external:
      name: ddev_default

volumes:
  postgres-volume:
